name = "MyAwesomePackage"
uuid = "a67a89a5-dc28-4765-a60d-3c9d54d71e04"
authors = ["Potatoespacecake <violetbirtwistle@gmail.com>"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "0.21, 0.22"
julia = "1.2.1"

